name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: Restore cached dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Run Tests
        run: yarn test
